name: Ubuntu Package Downloader and Builder

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Enter the Ubuntu package name (e.g., curl, git)'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Ubuntu
      run: sudo apt update

    - name: Install specified package
      run: |
        sudo apt update
        sudo apt install -y ${{ github.event.inputs.package }}

    - name: Package installed software and dependencies
      run: |
        # Create a directory to store the package files
        mkdir -p /tmp/package-backup
        # Use dpkg to list the installed package's dependencies and copy all relevant files
        dpkg-query -L ${{ github.event.inputs.package }} | xargs -I {} sudo cp --parents {} /tmp/package-backup/
        # Archive the directory into a tarball
        tar -czvf /tmp/${{ github.event.inputs.package }}.tar.gz -C /tmp package-backup

    - name: Upload packaged software
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.event.inputs.package }}.tar.gz
        path: /tmp/${{ github.event.inputs.package }}.tar.gz

    - name: Create Release with Package (Optional)
      if: success()
      uses: softprops/action-gh-release@v4
      with:
        files: /tmp/${{ github.event.inputs.package }}.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
