name: APT DEB Package Downloader

on:
  workflow_dispatch:
    inputs:
      packages:
        type: string
        description: 'Space-separated list of packages to download (e.g., curl gnupg2 ca-certificates lsb-release)'
        required: true

jobs:
  download_debs:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up environment
        run: |
          sudo apt update
          mkdir -p ~/debs

      - name: Download packages and dependencies
        run: |
          PACKAGES="${{ github.event.inputs.packages }}"
          echo "Downloading packages: $PACKAGES"
          sudo apt install --download-only -y $PACKAGES

      - name: Find downloaded .deb files
        id: find_debs
        run: |
          # 默认 apt 下载路径
          DEB_DIR="/var/cache/apt/archives"
          
          # 拷贝所有 .deb 到工作目录
          cp "$DEB_DIR"/*.deb ~/debs/
          
          # 统计数量
          count=$(ls ~/debs/*.deb | wc -l)
          echo "Found $count .deb files"
          echo "::set-output name=count::$count"

      - name: Archive .deb files
        if: steps.find_debs.outputs.count > 0
        run: |
          cd ~/ && tar czf debs.tar.gz debs/

      - name: Upload Artifact
        if: steps.find_debs.outputs.count > 0
        uses: actions/upload-artifact@v4
        with:
          name: deb-packages
          path: ~/debs.tar.gz
