name: Download APT Packages

on:
  workflow_dispatch:
    inputs:
      packages:
        description: '要下载的软件包列表，用空格分隔'
        required: true
        default: 'curl wget git'

jobs:
  download-packages:
    runs-on: ubuntu-22.04

    steps:
      - name: 创建下载目录
        run: mkdir -p ~/apt-packages

      - name: 下载软件包
        run: |
          sudo apt-get update
          sudo apt-get install --download-only ${{ github.event.inputs.packages }}
          cp /var/cache/apt/archives/*.deb ~/apt-packages/

      - name: 打包下载的软件包
        run: |
          cd ~
          tar -czvf apt-packages.tar.gz apt-packages/

      - name: 上传打包文件
        uses: actions/upload-artifact@v4
        with:
          name: apt-packages
          path: ~/apt-packages.tar.gz
          retention-days: 7    
