name: Download Multiple Debian Packages

on:
  workflow_dispatch:
    inputs:
      package_list:
        description: 'Comma-separated list of Debian packages (e.g., curl,wget,git)'
        required: true

jobs:
  download-packages:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Update package list and install wget
      run: |
        sudo apt-get update
        sudo apt-get install -y wget

    - name: Parse package list and download each package
      run: |
        mkdir -p ./downloaded_packages
        IFS=',' read -ra PKG_LIST <<< "${{ github.event.inputs.package_list }}"
        for pkg in "${PKG_LIST[@]}"; do
          # Trim leading and trailing whitespace from the package name
          trimmed_pkg=$(echo "$pkg" | xargs)
          echo "Downloading latest version of $trimmed_pkg..."
          apt-get download $(apt-cache madison $trimmed_pkg | head -n 1 | awk '{print $3}')
        done

    - name: Move downloaded files to the output directory
      run: |
        mv *.deb ./downloaded_packages/

    - name: Archive the downloaded packages
      run: |
        cd downloaded_packages && tar -czvf ../downloaded_packages.tar.gz *

    - name: Upload the archive as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: downloaded-packages-archive
        path: downloaded_packages.tar.gz



