name: Download Custom Deb Package

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: '要下载的deb包名称(例如: firefox)'
        required: true
        default: 'firefox'
      repository_url:
        description: '可选: 指定软件源URL'
        required: false
        default: ''
      gpg_key:
        description: '可选: 指定GPG密钥URL'
        required: false
        default: ''

jobs:
  download:
    runs-on: ubuntu-22.04
    steps:
      - name: 清理并准备环境
        run: |
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*
          sudo mkdir -p /tmp/deb-packages
        shell: bash

      - name: 添加自定义软件源(如有)
        if: github.event.inputs.repository_url != ''
        run: |
          echo "deb ${{ github.event.inputs.repository_url }} $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/custom.list
          if [ "${{ github.event.inputs.gpg_key }}" != "" ]; then
            wget -qO - ${{ github.event.inputs.gpg_key }} | sudo gpg --dearmor -o /usr/share/keyrings/custom-archive-keyring.gpg
          fi
          sudo apt-get update
        shell: bash

      - name: 更新包列表
        run: sudo apt-get update
        shell: bash

      - name: 下载deb包及其依赖
        run: |
          PACKAGE="${{ github.event.inputs.package_name }}"
          echo "准备下载包: $PACKAGE"
          
          # 下载包及其依赖
          sudo apt-get install -y --download-only $PACKAGE
          
          # 查找下载的deb文件
          DEB_FILES=$(sudo find /var/cache/apt/archives -name "*.deb" -type f)
          
          # 复制到临时目录
          for file in $DEB_FILES; do
            sudo cp "$file" /tmp/deb-packages/
          done
          
          # 创建tar包
          cd /tmp
          sudo tar -czvf deb-packages.tar.gz deb-packages/
          
          # 计算文件哈希
          SHA256=$(sha256sum deb-packages.tar.gz | awk '{print $1}')
          
          # 输出信息供后续步骤使用
          echo "deb_files=$DEB_FILES" >> $GITHUB_ENV
          echo "sha256=$SHA256" >> $GITHUB_ENV
        shell: bash

      - name: 显示下载信息
        run: |
          echo "成功下载以下deb包:"
          echo "$deb_files"
          echo "包文件哈希(SHA256): $sha256"
        shell: bash

      - name: 上传为构建产物
        uses: actions/upload-artifact@v4
        with:
          name: deb-packages
          path: /tmp/deb-packages.tar.gz
          retention-days: 7

      - name: 生成下载链接
        id: generate_url
        run: |
          DOWNLOAD_URL="https://github.com/${{ github.repository }}/suites/${{ github.run_id }}/artifacts/${{ github.run_number }}"
          echo "download_url=$DOWNLOAD_URL" >> $GITHUB_ENV
          echo "::set-output name=url::$DOWNLOAD_URL"
        shell: bash

      - name: 打印下载链接
        run: |
          echo "========================================="
          echo "下载链接: ${{ env.download_url }}"
          echo "包文件哈希(SHA256): ${{ env.sha256 }}"
          echo "========================================="
        shell: bash    
