name: DEB插件批量下载与打包

on:
  workflow_dispatch:
    inputs:
      plugins:
        description: '以空格分隔的插件名称列表（例如：nginx mysql redis）'
        required: true
        default: 'nginx mysql'

jobs:
  deb-package-manager:
    runs-on: ubuntu-22.04
    concurrency: self-hosted  # 防止并发冲突
    steps:
      - name: 初始化工作环境
        run: |
          # 创建专用目录结构
          mkdir -p /opt/deb-workspace/{downloads,packages}
          chmod 777 /opt/deb-workspace  # 确保有足够权限

      - name: 切换到root用户并更新包索引
        run: |
          echo "${{ secrets.ROOT_PASSWORD }}" | sudo -S -i
          export DEBIAN_FRONTEND=noninteractive
          apt-get update

      - name: 下载插件包及其依赖
        env:
          PLUGIN_LIST: ${{ github.event.inputs.plugins }}
          DOWNLOAD_DIR: /opt/deb-workspace/downloads
        run: |
          # 创建下载目录
          mkdir -p "$DOWNLOAD_DIR"
          
          # 使用apt-get下载DEB包及其依赖，不安装
          echo "${{ secrets.ROOT_PASSWORD }}" | sudo -S apt-get download $(echo $PLUGIN_LIST | tr ' ' '\n')
          
          # 移动下载的DEB包到指定目录
          mv *.deb "$DOWNLOAD_DIR"/

      - name: 验证文件完整性
        run: |
          cd /opt/deb-workspace/downloads
          for deb in *.deb; do
            echo "验证 $deb ..."
            dpkg-deb -I "$deb" > /dev/null || exit 1
          done

      - name: 创建安装包集合
        run: |
          cd /opt/deb-workspace
          tar -czvf packages.tar.gz downloads/*.deb
          echo "打包完成：packages.tar.gz"

      - name: 清理临时文件
        run: |
          rm -rf /opt/deb-workspace/downloads/*

      - name: 下载链接生成
        uses: actions/upload-artifact@v4
        with:
          name: deb-packages-$(date +%Y%m%d%H%M)
          path: /opt/deb-workspace/packages.tar.gz
          retention-days: 7  # 保留7天下载记录
    
