name: Download Debian Packages

on:
  workflow_dispatch:
    inputs:
      packages:
        description: 'List of packages to download (separated by spaces)'
        required: true

jobs:
  download-debs:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up environment
      run: |
        mkdir -p ~/debs/
        echo "DEBS_DIR=~/debs/" >> $GITHUB_ENV

    - name: Create debs.list file from input
      run: |
        echo "${{ github.event.inputs.packages }}" | tr ' ' '\n' > /tmp/debs.list

    - name: Download .deb files
      run: |
        echo "Downloading .deb files..."
        while read pkg; do
          if [[ "$pkg" =~ ^[a-zA-Z0-9\.\+\-]+$ ]]; then  # 确保是合法的包名
            echo "Downloading package: $pkg"
            sudo apt-get update
            sudo apt-get download "$pkg"
          else
            echo "Skipping invalid package name: $pkg"
          fi
        done < /tmp/debs.list

    - name: Move downloaded .deb files to DEBS_DIR
      run: |
        APT_CACHE_DIR=$(sudo apt-config shell Dir::Cache/apt Dir)
        APT_CACHE_DIR=${APT_CACHE_DIR#*=}
        if [ -z "$APT_CACHE_DIR" ]; then
          APT_CACHE_DIR="/var/cache/apt/archives"
        fi

        if ls "$APT_CACHE_DIR"/*.deb 1>/dev/null 2>&1; then
          sudo cp "$APT_CACHE_DIR"/*.deb "$DEBS_DIR/"
          count=$(ls "$DEBS_DIR"/*.deb | wc -l)
          echo "Found $count .deb files"
          echo "count=$count" >> $GITHUB_OUTPUT
        else
          echo "count=0" >> $GITHUB_OUTPUT
        fi

    - name: Upload .deb files as artifact
      uses: actions/upload-artifact@v4
      with:
        name: deb-packages
        path: ${{ env.DEBS_DIR }}



