name: Offline Package Download

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: 'Name of the package to download'
        required: true
        default: 'gcc'

jobs:
  download-packages:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create download directory
        run: |
          mkdir -p /home/tuners/1

      - name: Install aptitude
        run: |
          sudo apt-get update
          sudo apt-get install -y aptitude

      - name: Download package and its dependencies
        run: |
          sudo apt-get -d install ${{ github.event.inputs.package_name }}
          sudo mv /var/cache/apt/archives/*.deb /home/tuners/1

      - name: Install apt-rdepends
        run: |
          sudo apt-get install -y apt-rdepends

      - name: Download all dependencies
        run: |
          sudo apt download $(apt-rdepends ${{ github.event.inputs.package_name }} | grep -v "^ ")
          sudo mv /var/cache/apt/archives/*.deb /home/tuners/1

      - name: Package downloaded files
        run: |
          cd /home/tuners
          tar -zcvf ${{ github.event.inputs.package_name }}_offline.tar.gz 1

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.package_name }}_offline
          path: /home/tuners/${{ github.event.inputs.package_name }}_offline.tar.gz    
