name: Offline Package Download

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: '软件包名称'
        required: true
        type: string

jobs:
  download-packages:
    runs-on: ubuntu-22.04

    steps:
      - name: 创建保存目录
        run: mkdir -p /tmp/packages

      - name: 更新 apt 源并安装 aptitude 和 apt-rdepends
        run: |
          sudo apt-get update -y
          sudo apt-get install -y aptitude apt-rdepends

      - name: 下载指定软件包及其依赖
        run: |
          sudo apt-get -d install ${{ github.event.inputs.package_name }}
          sudo apt download $(apt-rdepends ${{ github.event.inputs.package_name }} | grep -v "^ ")

      - name: 移动下载的软件包
        run: sudo mv /var/cache/apt/archives/*.deb /tmp/packages

      - name: 打包下载的软件包
        run: |
          cd /tmp
          tar -czvf packages.tar.gz packages

      - name: 上传打包文件
        uses: actions/upload-artifact@v4
        with:
          name: offline-packages
          path: /tmp/packages.tar.gz
    
