name: Apt Package Download and Package with Dependencies

on:
  workflow_dispatch:
    inputs:
      apt_packages:
        description: '请填写 apt 包名称，多个用英文逗号分开'
        required: true
        default: 'curl,wget'  # 设置默认的 apt 包列表

jobs:
  download_and_package:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Update apt cache
      run: sudo apt-get update

    - name: Create a directory for packages
      run: mkdir -p apt_packages

    - name: Download apt packages and their dependencies
      run: |
        packages="${{ github.event.inputs.apt_packages }}"
        IFS=',' read -r -a package_array <<< "$packages"
        temp_dir=$(mktemp -d)
        for package in "${package_array[@]}"; do
          sudo apt-get download --print-uris "$package" | grep -oP '(?<=http://).*?(?=")' | xargs -I {} wget -P "$temp_dir" {}
        done
        mv "$temp_dir"/* apt_packages/
        rm -rf "$temp_dir"

    - name: Package downloaded apt packages
      run: |
        cd apt_packages
        for deb_file in *.deb; do
          package_name=$(dpkg-deb -f "$deb_file" Package)
          mkdir -p "$package_name"
          mv "$deb_file" "$package_name/"
          tar -czvf "$package_name.tar.gz" "$package_name"
          rm -rf "$package_name"
          echo "Successfully packed $package_name"
        done
        cd ..

    - name: List files for debugging
      run: |
        echo "Current working directory:"
        pwd
        echo "Contents of the current directory:"
        ls -R

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: apt-packages-artifact
        path: apt_packages/**/*.tar.gz
        retention-days: 1
        if-no-files-found: warn
        compression-level: 6
        overwrite: false
        include-hidden-files: false