name: Npm Package Download and Package

on:
  workflow_dispatch:
    inputs:
      npm_packages:
        description: '请填写 npm 包名称，多个用英文逗号分开'
        required: true
        default: 'lodash,axios'  # 设置默认的 npm 包列表

jobs:
  download_and_package:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Create a directory for packages
      run: mkdir -p npm_packages

    - name: Download and package npm packages
      run: |
        packages="${{ github.event.inputs.npm_packages }}"
        IFS=',' read -r -a package_array <<< "$packages"
        for package in "${package_array[@]}"; do
          mkdir -p "npm_packages/$package"
          cd "npm_packages/$package"
          if npm pack "$package" --pack-destination .; then
            tar -czvf "$package.tar.gz" *.tgz
            rm *.tgz
            echo "Successfully packed $package"
          else
            echo "Failed to pack $package. Error details:"
            npm pack "$package" --pack-destination . 2>&1
          fi
          cd ../..
        done
    - name: List files for debugging
      run: |
        echo "Current working directory:"
        pwd
        echo "Contents of the current directory:"
        ls -R
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: npm-packages-artifact
        path: npm_packages/**/*.tar.gz
        retention-days: 1
        if-no-files-found: warn
        compression-level: 6
        overwrite: false
        include-hidden-files: false