name: Npm Package Offline Pack

on:
  workflow_dispatch:
    inputs:
      npm_packages:
        description: '请填写 npm 包名称，多个用英文逗号分开'
        required: true
        default: 'lodash,axios'  # 设置默认的 npm 包列表

jobs:
  download_and_package:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '23'

    - name: Create a directory for packages
      run: mkdir -p npm_packages

    - name: Download npm packages and their dependencies
      run: |
        packages="${{ github.event.inputs.npm_packages }}"
        IFS=',' read -r -a package_array <<< "$packages"
        for package in "${package_array[@]}"; do
          mkdir -p "npm_packages/$package"
          cd "npm_packages/$package"
          npm install --offline --package-lock-only "$package"
          # 模拟离线下载包和依赖
          npm install --prefer-offline --package-lock-only --verbose
          npm pack
          cd ../..
        done

    - name: Package all downloaded packages
      run: |
        tar -czvf npm_packages.tar.gz npm_packages

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: npm-packages-offline-artifact
        path: npm_packages.tar.gz
        retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天