name: windows Python whl Packager

on:
  workflow_dispatch:
    inputs:
      python_version:
        description: '请输入 Python 版本 (例如: 3.8)'
        required: true
        default: '3.8'
      packages:
        description: '请输入要下载的 PyPI 插件名称和版本，多个用逗号分隔 (例如: requests==2.28.1, numpy==1.23.5)'
        required: true
        default: 'requests==2.28.1'

jobs:
  package-python-plugins:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ github.event.inputs.python_version }}

      - name: Create download directory
        run: New-Item -ItemType Directory -Name python_plugin_packages

      - name: Download packages
        run: |
          $packages = "${{ github.event.inputs.packages }}".Split(',')
          foreach ($package in $packages) {
            pip download $package -d python_plugin_packages
          }

      - name: Package downloaded packages
        run: Compress-Archive -Path python_plugin_packages -DestinationPath python_plugin_pack.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-plugin-pack
          path: python_plugin_pack.zip
    
